
services:

  traefik:
    image: traefik:latest
    container_name: passbolt_traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - ./traefik/traefik.yaml:/traefik.yaml:ro
      - ./traefik/conf/:/etc/traefik/conf
      - ssl:/etc/ssl
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt
    environment:
      - DATASOURCES_DEFAULT_HOST=${DATASOURCES_DEFAULT_HOST}
      - DATASOURCES_DEFAULT_USERNAME=${DATASOURCES_DEFAULT_USERNAME}
      - DATASOURCES_DEFAULT_PASSWORD=${DATASOURCES_DEFAULT_PASSWORD}
      - DATASOURCES_DEFAULT_DATABASE=${DATASOURCES_DEFAULT_DATABASE}
      - APP_FULL_BASE_URL=https://${APP_DOMAIN}
      - EMAIL_DEFAULT_FROM=${APP_EMAIL}
    labels:
      - traefik.enable=true

      - traefik.http.routers.passbolt-http.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.passbolt-http.entrypoints=web
      - traefik.http.routers.passbolt-http.middlewares=SslHeader@file

      - traefik.http.routers.passbolt-https.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.passbolt-https.entrypoints=websecure
      - traefik.http.routers.passbolt-https.middlewares=SslHeader@file
      - traefik.http.routers.passbolt-https.tls=true
      - traefik.http.routers.passbolt-https.tls.certresolver=${TRAEFIK_CERT_RESOLVER}
    volumes:
      - passbolt_gpg:/etc/passbolt/gpg
      - passbolt_jwt:/etc/passbolt/jwt
    restart: unless-stopped

volumes:
  passbolt_gpg:
  passbolt_jwt:
  letsencrypt:
  ssl:
